dist: trusty
sudo: false
#before_install:
#  - sudo apt-get install libgtest-dev
 # - cd /usr/src/gtest
  #- sudo cmake CMakeLists.txt
  #- sudo make
  #- sudo cp *.a /usr/lib
 
# Enable C++ support
language: cpp

# Sonar integration for code that smells :)
#addons:
 # sonarcloud:
  #  - organization: Dovantech Github
   # - token:
    #   secure: dafe9422fd40d91e2cf44d7465d9b9fec4db6e9e

script:
 #- sonarqube
 - mkdir build
 - cd build
 - make
 - ./friends_lib_test
 
#Cache:
#  directories:
 # $HOME/.sonar/cache
  #$HOME/.gradle
