dist: trusty
sudo: required
before_install:
  - sudo apt-get install libgtest-dev cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
 
# Enable C++ support
language: cpp

# Sonar integration for code that smells :)
#addons:
 # sonarcloud:
  #  - organization: Dovantech Github
   # - token:
    #   secure: dafe9422fd40d91e2cf44d7465d9b9fec4db6e9e

script:
 #- sonarqube
 - sudo mkdir build
 - cd build
 - sudo cmake ..
 - sudo make
 - sudo ./friends_lib_test
 
#Cache:
#  directories:
 # $HOME/.sonar/cache
  #$HOME/.gradle
